pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                deleteDir()
                checkout scm
            }
        }
        stage('Test') {
            steps {
                sh 'mvn verify'
            }
        }
        stage('Build & Push Docker Image') {
            steps {
                sh 'docker build --platform linux/amd64 -t cc-ms-k8s-training.common.repositories.cloud.sap/bulletin-board-i320726 .'
                withCredentials([usernamePassword(credentialsId: 'registry-user', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh 'docker login -u $USERNAME -p $PASSWORD cc-ms-k8s-training.common.repositories.cloud.sap'
                }
                sh 'docker push cc-ms-k8s-training.common.repositories.cloud.sap/bulletin-board-i320726'
            }
        }
        
    }
}